version: '3.8'

services:
  # Company Website - www.ajinsights.app
  company-website:
    build: 
      context: ../aj-insights_com_au
      dockerfile: Dockerfile
    container_name: ajinsights-website
    ports:
      - "3102:3102"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3102/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Documentation Site - docs.ajinsights.app
  documentation:
    build:
      context: ../local-agentic-ai-comprehensive-documentation
      dockerfile: Dockerfile
    container_name: ajinsights-docs
    ports:
      - "3103:80"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=https://docs.ajinsights.app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AI Platform Services - agentic-ai.ajinsights.app
  abs-agent-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: abs-agent-backend
    ports:
      - "30080:8000"
    environment:
      - NODE_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge
    name: ajinsights-network

volumes:
  website-data:
  docs-data: